/**
 * Compatibility facade over the canonical model registry.
 * Prefer importing from `src/models/modelRegistry` for new code.
 */

export {
  AVAILABLE_MODEL_IDS,
  AVAILABLE_MODELS,
  DEFAULT_EVALUATION_MODEL_ID,
  DEFAULT_REASONING_EFFORT,
  DEFAULT_RUN_MODEL_ID,
  MOCK_MODEL_ID,
  MODEL_REGISTRY,
  OPENAI_MODEL_ID,
  OPENAI_MODELS,
  REASONING_EFFORTS,
  displayNameForModel,
  getModelDefinition,
  isMockModel,
  isOpenAIModel,
  isReasoningEffort,
  isRegisteredModel,
  labelForModel,
  modelSelectGroups,
  modelSupportsCustomTemperature,
  modelSupportsReasoningEffort,
  modelsForEvaluation,
  modelsForRun,
  providerForModel,
  shortLabelForModel,
  supportedOpenAIModelList,
  tierLabel,
  formatReasoningEffort,
  type ModelDefinition,
  type ModelOption,
  type ModelProvider,
  type ModelSelectGroup,
  type ModelTier,
  type OpenAIModelId,
  type ReasoningEffort,
} from "../models/modelRegistry";
